name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Update version number
        run: |
          # Determine the version change type based on commit message
          if [[ "${{ github.event.head_commit.message }}" =~ "#major" ]]; then
            npm version major --no-git-tag-version
          elif [[ "${{ github.event.head_commit.message }}" =~ "#minor" ]]; then
            npm version minor --no-git-tag-version
          else
            npm version patch --no-git-tag-version
          fi

          # Update manifest.json version
          VERSION=$(npm pkg get version | tr -d '"')
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/g" public/manifest.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Bump version to $VERSION [skip ci]" -a
          git push
    
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Zip files
        run: zip -r extension.zip dist/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: extension.zip
          tag_name: $VERSION
          name: Release $VERSION
    
      - name: Publish to Chrome Web Store
        uses: Klemensas/chrome-extension-upload-action@v1
        with:
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          file-name: './extension.zip'
          app-id: 'fockmbfncdacmjbmieenodfeblmneaii'
          publish: true